### ISSUE TITLE
Errors on x86-32

### ISSUE THREAD

**Issue by StarSmasher44** [sammy007/monero-stratum#50]
I have followed every instruction fully, I ended up with everything ready but I get stopped by an error when I try to launch the stratum itself;

`2017/09/24 18:37:56 Running with 2 threads
2017/09/24 18:37:56 Upstream: Main => http://127.0.0.1:18081/json_rpc
2017/09/24 18:37:56 Default upstream: Main => http://127.0.0.1:18081/json_rpc
2017/09/24 18:37:56 Set block refresh every 1s
2017/09/24 18:37:56 Stratum listening on 0.0.0.0:5555
2017/09/24 18:37:56 Stratum listening on 0.0.0.0:1111
2017/09/24 18:37:56 Stratum listening on 0.0.0.0:3333
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x823b4fc]

goroutine 6 [running]:
panic(0x835f200, 0x94eea030)
	/usr/lib/go-1.6/src/runtime/panic.go:481 +0x326
sync/atomic.AddUint64(0x94f2b01c, 0x1, 0x0, 0x94f61fd4, 0x4)
	/usr/lib/go-1.6/src/sync/atomic/asm_386.s:112 +0xc
github.com/sammy007/monero-stratum/rpc.(*RPCClient).markSick(0x94f2afc0)
	/home/laser50/Desktop/monero/monero-stratum/build/_workspace/src/github.com/sammy007/monero-stratum/rpc/rpc.go:128 +0x5a
github.com/sammy007/monero-stratum/rpc.(*RPCClient).doPost(0x94f2afc0, 0x94ed5c40, 0x1f, 0x83d6780, 0x10, 0x82f9680, 0x94ed5c20, 0x0, 0x0, 0x0)
	/home/laser50/Desktop/monero/monero-stratum/build/_workspace/src/github.com/sammy007/monero-stratum/rpc/rpc.go:88 +0x4bd
github.com/sammy007/monero-stratum/rpc.(*RPCClient).GetBlockTemplate(0x94f2afc0, 0x8, 0x94f42660, 0x5f, 0x0, 0x0, 0x0)
	/home/laser50/Desktop/monero/monero-stratum/build/_workspace/src/github.com/sammy007/monero-stratum/rpc/rpc.go:63 +0x196
github.com/sammy007/monero-stratum/stratum.(*StratumServer).fetchBlockTemplate(0x94f38900, 0x0)
	/home/laser50/Desktop/monero/monero-stratum/build/_workspace/src/github.com/sammy007/monero-stratum/stratum/blocks.go:34 +0x77
github.com/sammy007/monero-stratum/stratum.(*StratumServer).refreshBlockTemplate(0x94f38900, 0x0)
	/home/laser50/Desktop/monero/monero-stratum/build/_workspace/src/github.com/sammy007/monero-stratum/stratum/handlers.go:130 +0x21
created by github.com/sammy007/monero-stratum/stratum.NewStratum
	/home/laser50/Desktop/monero/monero-stratum/build/_workspace/src/github.com/sammy007/monero-stratum/stratum/stratum.go:102 +0x776
`

I'm not sure what it means or how to resolve it, so some help would be very appreciated!

**Comment by sammy007** [comment]
Update golang, looks like golang is fucked up. What architecture? Is it amd64 or some arm hardware?

**Comment by StarSmasher44** [comment]
Golang seems updated, also it is a 32 bit OS, and yeah I think amd64

**Comment by sammy007** [comment]
If it's 32 bit OS it's not an amd64. I see why you are getting this, I need to update code, there is a known issue with golang structs and int fields.

**Comment by sammy007** [comment]
Must be fixed by https://github.com/sammy007/monero-stratum/commit/bf0ffb035f13898dfc93d9281f83aa1114212f75

Don't shy to report such issues because I have no ARM or x86-32 to test. I need to know also if this fix works, so don't just abandon this thread, tell me if it fixed or not.

**Comment by sammy007** [comment]
For reference: https://golang.org/pkg/sync/atomic/#pkg-note-BUG

**Comment by StarSmasher44** [comment]
It may be related to me running this 32-bit ubuntu OS through a virtual machine, I chose 32 bit because I wouldn't be using more than 4 GB any way, could the VM be a problem in this instance?

EDIT: issue remains the same, same error code and everything :\

**Comment by sammy007** [comment]
Did you `make clean` before `make` again? Also need trace again because it could be slightly different.

**Comment by StarSmasher44** [comment]
It worked, I forgot to clean, great! Only issue keeping me now is https://puu.sh/xHYFV/64d5b82357.png that but I think its network-related. You can consider the previous one fixed!

**Comment by sammy007** [comment]
Yes, network. Closing.

**Comment by StarSmasher44** [comment]
Hope I'm not being an annoying shit right now, but you wouldn't know how to fix this right? I've tried messing with the ports and IP and some firewall changes, but they remain mostly the same

**Comment by sammy007** [comment]
Firewall? You configured stratum to connect to monerod's rpc on `localhost:18081`. It can't. So no daemon running there on the same machine or you misconfigured.
